carts/urls.py
from django.conf.urls import url
from carts import views

urlpatterns = [
    url(r'^update_cart/(?P<item_id>[0-9]+)/$', views.actualitzar_carret, name='actualitzarCarret'),
    url(r'^show_sales_order/$', views.veure_comanda, name='veureComanda'),
    url(r'^show_sales_order/cart_confirmation/$', views.confirmar_carret, name='confirmarCarret'),
    url(r'^show_sales_order/delete_line/(?P<item_id>[0-9]+)/$', views.esborrar_linia, name='esborrarLinia'),
    url(r'^show_sales_order/delete_sales_order/$', views.esborrar_comanda, name='esborrarComanda'),
    url(r'^sales_list/$', views.llista_comandes, name='llistaComandes'),
    url(r'^sales_list/order_details/(?P<comanda_id>[0-9]+)/$', views.detall_comanda, name='detallComanda')
]

items/urls.py
from django.conf.urls import url
from items import views

urlpatterns = [
    url(r'^$', views.items, name='items'),
    url(r'^item/', views.infoitem, name='infoItem'),
    url(r'^add_item/$', views.item, name='addItem'),
    url(r'^edit_item/(?P<item_id>[0-9]+)/$', views.item, name='editItem'),
    url(r'^remove_item/(?P<item_id>[0-9]+)/$', views.removeitem, name='removeItem'),
    url(r'^categories/$', views.categories, name='categories'),
    url(r'^add_category/$', views.category, name='addCategory'),
    url(r'^edit_category/(?P<category_id>[0-9]+)/$', views.category, name='editCategory'),
    url(r'^remove_category/(?P<category_id>[0-9]+)/$', views.removecategory, name='removeCategory'),
    url(r'^manufacturers/$', views.manufacturers, name='manufacturers'),
    url(r'^add_manufacturer/$', views.manufacturer, name='addManufacturer'),
    url(r'^edit_manufacturer/(?P<manufacturer_id>[0-9]+)/$', views.manufacturer, name='editManufacturer'),
    url(r'^remove_manufacturer/(?P<manufacturer_id>[0-9]+)/$', views.removemanufacturer, name='removeManufacturer')
]

sun2/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from users.views import vista_login, vista_logout, vista_registre, vista_perfil, vista_clau

urlpatterns = (
    [
        url(r'^admin/', admin.site.urls),
        url(r'^', include('items.urls', namespace="items")),
        url(r'^cart/', include('carts.urls', namespace="carts")),
        url(r'^backups/', include('backups.urls', namespace="backups")),
        url(r'^login/$', vista_login, name="login"),
        url(r'^logout/$', vista_logout, name="logout"),
        url(r'^registration/$', vista_registre, name="registration"),
        url(r'^profile/$', vista_perfil, name="profile"),
        url(r'^profile/reset/$', vista_clau, name="resetPassword")
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

items/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

class Categoria(models.Model):
    nom = models.CharField(verbose_name="Nom", max_length=20, help_text="El nom de la categoria del producte.")

    def __unicode__(self):
        return u'%s' % (self.nom)

class Fabricant(models.Model):
    nom = models.CharField(verbose_name="Nom", max_length=20, help_text="El nom del fabricant del producte.")

    def __unicode__(self):
        return u'%s' % (self.nom)

class Producte(models.Model):
    nom = models.CharField(verbose_name="Nom", max_length=20, help_text="El nom del producte.")
    preu = models.DecimalField(verbose_name="Preu", max_digits=5, decimal_places=2, help_text="El preu del producte.")
    quantitat = models.PositiveIntegerField(verbose_name="Stock", help_text="La quantitat d'existències.")
    resum = models.TextField(verbose_name="Resum", max_length=1000, help_text="El resum del producte.")
    descripcio = models.CharField(verbose_name="Descripció", max_length=100, help_text="La descripció del producte.")
    categories = models.ManyToManyField(Categoria, verbose_name="Categoria", help_text="La categoria del producte.")
    fabricant = models.ForeignKey(Fabricant, verbose_name="Fabricant", help_text="El fabricant del producte.")
    imatge = models.ImageField(verbose_name="Imatge", upload_to='i_logo', height_field=None, width_field=None, max_length=100, help_text="La imatge del producte.")
    video = models.CharField(verbose_name="Demostració", max_length=150, null=True, blank=True, help_text="La demostració mitjançant una URL d'un vídeo.")

    class Meta:
        unique_together = [('nom', 'fabricant')]

    def mostra_categories(self):
        return u", ".join([c.nom for c in self.categories.all()])

    def mostra_categories_id(self):
        return u", ".join([unicode(c.id) for c in self.categories.all()])

    def __unicode__(self):
        return u'%s' % (self.nom)

items/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.views.decorators.csrf import ensure_csrf_cookie
from django.forms import modelform_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit
from items.models import Categoria, Fabricant, Producte
import json

@ensure_csrf_cookie
def items(request):
    items_list=Producte.objects.all()
    context={'items_list':items_list}
    return render(request,'items/items.html',context)

def infoitem(request):
    info=json.loads(request.body)
    item=Producte.objects.get(pk=info['id'])
    infoitem={'nom':item.nom,'resum':item.resum,'video':item.video}
    resposta=json.dumps({'resposta':infoitem});
    return HttpResponse(resposta,content_type='application/json');

@user_passes_test(lambda u:u.is_staff, login_url='/login/')
def categories(request):
    categories_list=Categoria.objects.all()
    context={'categories_list':categories_list}
    return render(request,'items/categories.html',context)

@user_passes_test(lambda u:u.is_staff, login_url='/login/')
def manufacturers(request):
    manufacturers_list=Fabricant.objects.all()
    context={'manufacturers_list':manufacturers_list}
    return render(request,'items/manufacturers.html',context)

@user_passes_test(lambda u:u.is_staff, login_url='/login/')
def item(request,item_id=None):
    esModificacio=(item_id!=None)
    addItemForm=modelform_factory(Producte,exclude=())
    if esModificacio:
        item=get_object_or_404(Producte,pk=item_id)
    else:
        item=Producte()
    if request.method=='POST':
        form=addItemForm(request.POST,request.FILES,instance=item)
        if form.is_valid():
            item=form.save()
            messages.success(request,'El producte s\'ha desat correctament')
            return HttpResponseRedirect(reverse('items:items'))
        else:
            messages.error(request,'Hi ha errors en el formulari')
    else:
        form=addItemForm(instance=item)

    form.helper=FormHelper()
    form.helper.form_class='blueForms'
    form.helper.label_class='col-lg-2'
    form.helper.field_class='col-lg-10'
    form.helper.add_input(Submit('submit','Desar'))
    return render(request,'forms/form.html',{'form':form})

@user_passes_test(lambda u:u.is_staff, login_url='/login/')
def category(request,category_id=None):
    esModificacio=(category_id!=None)
    addCategoryForm=modelform_factory(Categoria,exclude=())
    if esModificacio:
        category=get_object_or_404(Categoria,pk=category_id)
    else:
        category=Categoria()
    if request.method=='POST':
        form=addCategoryForm(request.POST,request.FILES,instance=category)
        if form.is_valid():
            category=form.save()
            messages.success(request,'La categoria s\'ha desat correctament')
            return HttpResponseRedirect(reverse('items:categories'))
        else:
            messages.error(request,'Hi ha errors en el formulari')
    else:
        form=addCategoryForm(instance=category)

    form.helper=FormHelper()
    form.helper.form_class='blueForms'
    form.helper.label_class='col-lg-2'
    form.helper.field_class='col-lg-10'
    form.helper.add_input(Submit('submit','Desar'))
    return render(request,'forms/form.html',{'form':form})

@user_passes_test(lambda u:u.is_staff, login_url='/login/')
def manufacturer(request,manufacturer_id=None):
    esModificacio=(manufacturer_id!=None)
    addManufacturerForm=modelform_factory(Fabricant,exclude=())
    if esModificacio:
        manufacturer=get_object_or_404(Fabricant,pk=manufacturer_id)
    else:
        manufacturer=Fabricant()
    if request.method=='POST':
        form=addManufacturerForm(request.POST,request.FILES,instance=manufacturer)
        if form.is_valid():
            manufacturer=form.save()
            messages.success(request,'El fabricant s\'ha desat correctament')
            return HttpResponseRedirect(reverse('items:manufacturers'))
        else:
            messages.error(request,'Hi ha errors en el formulari')
    else:
        form=addManufacturerForm(instance=manufacturer)

    form.helper=FormHelper()
    form.helper.form_class='blueForms'
    form.helper.label_class='col-lg-2'
    form.helper.field_class='col-lg-10'
    form.helper.add_input(Submit('submit','Desar'))
    return render(request,'forms/form.html',{'form':form})

@user_passes_test(lambda u:u.is_staff, login_url='/login/')
def removeitem(request,item_id):
    item=get_object_or_404(Producte,pk=item_id)
    messages.success(request,'El producte s\'ha eliminat correctament')

    item.delete()
    return HttpResponseRedirect(reverse('items:items'))

@user_passes_test(lambda u:u.is_staff, login_url='/login/')
def removecategory(request,category_id):
    category=get_object_or_404(Categoria,pk=category_id)
    messages.success(request,'La categoria s\'ha eliminat correctament')

    category.delete()
    return HttpResponseRedirect(reverse('items:categories'))

@user_passes_test(lambda u:u.is_staff, login_url='/login/')
def removemanufacturer(request,manufacturer_id):
    manufacturer=get_object_or_404(Fabricant,pk=manufacturer_id)
    messages.success(request,'El fabricant s\'ha eliminat correctament')

    manufacturer.delete()
    return HttpResponseRedirect(reverse('items:manufacturers'))

items/templates/items/categories.html
{% extends 'base.html' %} {% block content %}
<div class="panel-heading">Categories</div>
<div class="panel-body">
    {% if categories_list %} {% for category in categories_list %}
    <div class="col-xs-12 col-sm-6 col-md-4">
        <div id="category" class="panel panel-default">
            <div class="panel-body">
                {{category.nom}}
                <div class="pull-right">
                    <a class="wall-entry icon-space-right" href="{% url 'items:editCategory' category.pk %}">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    <a class="wall-entry" href="{% url 'items:removeCategory' category.pk %}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %} {% else %}
    <p>No hi ha categories a la llista, <a href="{% url 'items:addCategory' %}">afegeix-ne una</a>.</p>
    {% endif %}
</div>
{% endblock %}

items/templates/items/items.html
{% extends 'base.html' %} {% load staticfiles %} {% block css %}
<!-- Base Design -->
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<!-- Item Design -->
<link href="{% static 'css/item.css' %}" rel="stylesheet"> {% endblock %} {% block navbar %} {% if items_list %}
<ul class="nav navbar-nav">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Productes <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="#" data-filter="all">Totes les categories</a></li>
            <li role="separator" class="divider"></li>
            {% if categories %} {% for category in categories %}
            <li><a href="#" data-filter="{{category.pk}}">{{category}}</a></li>
            {% endfor %} {% else %}
            <li><a href="#">No hi ha cap categoria</a></li>
            {% endif %}
        </ul>
    </li>
</ul>
<form class="navbar-form navbar-left" role="search">
    <div class="input-group">
        <input type="text" class="form-control filtr-search" name="filtr-search" data-search placeholder="Cerca...">
        <span class="input-group-btn">
            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
        </span>
    </div>
</form>
{% endif %} {% endblock %} {% block content %}
<div class="panel-heading">Productes</div>
<div class="panel-body" ng-controller="ItemsController">
    {% include 'partials/layout_modal.html' %}
    <div class="filtr-container">
        {% if items_list %} {% for item in items_list %}
        <div class="col-xs-12 col-sm-6 col-md-4 filtr-item" data-category="{{item.mostra_categories_id}}" data-sort="{{item.nom}}">
            <div id="item" class="panel panel-item panel-default panel-item-default">
                <div class="panel-heading">
                    {{item.nom}}
                    <div class="pull-right">
                        <a class="wall-entry" href="#" ng-click="veureProducte({{item.pk}})" data-toggle="modal" data-target="#modal-item">
                            <span class="glyphicon glyphicon-eye-open"></span>
                        </a>
                        {% if not user.is_staff %}
                        <a class="wall-entry icon-space-left" href="{% url 'carts:actualitzarCarret' item.pk %}">
                            <span class="glyphicon glyphicon-shopping-cart"></span>
                        </a>
                        {% endif %} {% if user.is_staff %}
                        <a class="wall-entry icon-space-all" href="{% url 'items:editItem' item.pk %}">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <a class="wall-entry" href="{% url 'items:removeItem' item.pk %}">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                        {% endif %}
                    </div>
                </div>
                <div class="panel-body">
                    <div class="media">
                        <img class="media-object img-responsive img-thumbnail" src="{{item.imatge.url}}" alt="{{item.nom}}" style="width:100%" />
                        <div class="media-body">
                            <p><span class="label label-primary span-margin-bottom">{{item.mostra_categories}}</span></p>
                            <p>{{item.descripcio}}</p>
                            <p><b>Preu:</b> {{item.preu}} €</p>
                            <p><b>Stock:</b> {{item.quantitat}} unitat/s</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %} {% else %}
        <p>No hi ha productes a la llista.</p>
        {% endif %}
    </div>
</div>
{% endblock %} {% block scripts %}
<!-- Angular -->
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js" type="text/javascript"></script>
<!-- Angular Cookies -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.0/angular-cookies.js" type="text/javascript"></script>
<!-- Angular InfoItem -->
<script src="{% static 'js/modal-item.js' %}" type="text/javascript"></script>
<!-- Filterizr -->
<script src="{% static 'js/jquery.filterizr.js' %}" type="text/javascript"></script>
<!-- Kick off Filterizr -->
<script src="{% static 'js/initialize.filterizr.js' %}" type="text/javascript"></script>
<!-- Modal Restart Video -->
<script src="{% static 'js/modal-rv.js' %}" type="text/javascript"></script>
{% endblock %}

items/templates/items/manufacturers.html
{% extends 'base.html' %} {% block content %}
<div class="panel-heading">Fabricants</div>
<div class="panel-body">
    {% if manufacturers_list %} {% for manufacturer in manufacturers_list %}
    <div class="col-xs-12 col-sm-6 col-md-4">
        <div id="manufacturer" class="panel panel-default">
            <div class="panel-body">
                {{manufacturer.nom}}
                <div class="pull-right">
                    <a class="wall-entry" href="{% url 'items:editManufacturer' manufacturer.pk %}">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    <a class="wall-entry" href="{% url 'items:removeManufacturer' manufacturer.pk %}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %} {% else %}
    <p>No hi ha fabricants a la llista, <a href="{% url 'items:addManufacturer' %}">afegeix-ne un</a>.</p>
    {% endif %}
</div>
{% endblock %}