carts/urls.py
from django.conf.urls import url
from carts import views

urlpatterns = [
    url(r'^update_cart/(?P<item_id>[0-9]+)/$', views.actualitzar_carret, name='actualitzarCarret'),
    url(r'^show_sales_order/$', views.veure_comanda, name='veureComanda'),
    url(r'^show_sales_order/cart_confirmation/$', views.confirmar_carret, name='confirmarCarret'),
    url(r'^show_sales_order/delete_line/(?P<item_id>[0-9]+)/$', views.esborrar_linia, name='esborrarLinia'),
    url(r'^show_sales_order/delete_sales_order/$', views.esborrar_comanda, name='esborrarComanda'),
    url(r'^sales_list/$', views.llista_comandes, name='llistaComandes'),
    url(r'^sales_list/order_details/(?P<comanda_id>[0-9]+)/$', views.detall_comanda, name='detallComanda')
]

sun2/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from users.views import vista_login, vista_logout, vista_registre, vista_perfil, vista_clau

urlpatterns = (
    [
        url(r'^admin/', admin.site.urls),
        url(r'^', include('items.urls', namespace="items")),
        url(r'^cart/', include('carts.urls', namespace="carts")),
        url(r'^backups/', include('backups.urls', namespace="backups")),
        url(r'^login/$', vista_login, name="login"),
        url(r'^logout/$', vista_logout, name="logout"),
        url(r'^registration/$', vista_registre, name="registration"),
        url(r'^profile/$', vista_perfil, name="profile"),
        url(r'^profile/reset/$', vista_clau, name="resetPassword")
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

carts/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

class Comanda(models.Model):
    comanda_id = models.AutoField(primary_key=True)
    usuari = models.ForeignKey(User)
    data = models.DateField(auto_now=True)
    carrer = models.CharField(verbose_name="Carrer", max_length=50, help_text="El nom del carrer on enviarem la comanda.")
    poblacio = models.CharField(verbose_name="Població", max_length=30, help_text="La població a la qual pertany el carrer.")
    codi_postal = models.PositiveIntegerField(verbose_name="Codi Postal", help_text="El codi postal de la població.")
    provincia = models.CharField(verbose_name="Província", max_length=30, help_text="La província a la qual pertany la població.")
    estats = (('T', 'Tramitant-se'),
              ('E', 'Enviat')
              )
    estat = models.CharField(max_length=1, choices=estats, default='T')

class Linia(models.Model):
    linia_id = models.AutoField(primary_key=True)
    comanda_id = models.ForeignKey('Comanda')
    producte_id = models.ForeignKey('items.Producte')
    preu = models.DecimalField(max_digits=5, decimal_places=2)
    quantitat = models.PositiveIntegerField()

carts/forms.py
from django import forms

class edit_cart(forms.Form):
    quantitat = forms.IntegerField(min_value=1, widget=forms.NumberInput(attrs={'autofocus':'autofocus'}))

carts/views.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.forms import modelform_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit
from carts.models import Comanda, Linia
from items.models import Categoria, Producte
from .forms import edit_cart

def actualitzar_carret(request,item_id):
    pdt=get_object_or_404(Producte,pk=item_id)
    if request.method=='POST':
        form=edit_cart(request.POST)
        if form.is_valid():
            if 'carret' not in request.session:
                request.session['carret']={}
            qnt=form.cleaned_data['quantitat']
            if qnt>pdt.quantitat:
                messages.error(request,'No hi ha suficients existències, actualment tenim ' + unicode(pdt.quantitat) + ' unitat/s')
            else:
                request.session['carret'].update({item_id:qnt})
                messages.add_message(request,messages.SUCCESS,'El producte s\'ha afegit dins el carret')
                return HttpResponseRedirect(reverse('items:items'))
        else:
            messages.error(request,'Hi ha errors en el formulari')
    else:
        form=edit_cart()

    form.helper=FormHelper()
    return render(request,'carts/edit_cart.html',{'form':form,'producte':pdt})

def veure_comanda(request):
    if 'carret' not in request.session:
        request.session['carret']={}
    ui_cart=[]
    preu_comanda=0
    for id in request.session['carret']:
        pdt=Producte.objects.get(id=id)
        qnt=request.session['carret'][id]
        pre=pdt.preu*qnt
        preu_comanda+=pre
        ui_cart.append({'producte':pdt,
                        'quantitat':qnt,
                        'preu':pre
                        })
    return render(request,'carts/cart.html',{'ui_cart':ui_cart,'preu_comanda':preu_comanda})

def esborrar_linia(request,item_id):
    request.session.modified=True
    pdt=request.session['carret']
    if item_id in pdt:
        del pdt[item_id]
    return HttpResponseRedirect(reverse('carts:veureComanda'))

def esborrar_comanda(request):
    if 'carret' in request.session:
        request.session['carret']={}
    return HttpResponseRedirect(reverse('carts:veureComanda'))

@user_passes_test(lambda u:u.is_authenticated(), login_url='/login/')
def confirmar_carret(request):
    addConfirmCartForm=modelform_factory(Comanda,exclude=('comanda_id','usuari','data','estat'))
    cmd=Comanda()
    if request.method=='POST':
        form=addConfirmCartForm(request.POST,request.FILES,instance=cmd)
        if form.is_valid():
            carrer=form.cleaned_data['carrer']
            poblacio=form.cleaned_data['poblacio']
            codi_postal=form.cleaned_data['codi_postal']
            provincia=form.cleaned_data['provincia']
            if 'carret' in request.session:
                if request.session['carret']:
                    cmd.carrer=carrer
                    cmd.poblacio=poblacio
                    cmd.codi_postal=codi_postal
                    cmd.provincia=provincia
                    cmd.usuari=request.user
                    cmd.save()
                    crt=request.session['carret']
                    for id in crt:
                        pdt=Producte.objects.get(id=id)
                        qnt=crt[id]
                        if qnt>pdt.quantitat:
                            messages.error(request,'No hi ha suficients existències')
                            return HttpResponseRedirect(reverse('carts:veureComanda'))
                        else:
                            linia=Linia()
                            linia.comanda_id=cmd
                            linia.producte_id=pdt
                            linia.quantitat=qnt
                            linia.preu=pdt.preu
                            linia.save()
                            pdt.quantitat=pdt.quantitat-qnt
                            pdt.save()
                            request.session['carret']={}
                    return HttpResponseRedirect(reverse('carts:llistaComandes'))
                else:
                    messages.error(request,'No hi ha cap producte al carret')
            else:
                return HttpResponseRedirect(reverse('items:items'))
        else:
            messages.error(request,'Hi ha errors en el formulari')
    else:
        form=addConfirmCartForm(instance=cmd)

    form.helper=FormHelper()
    form.helper.form_class='blueForms'
    form.helper.label_class='col-lg-2'
    form.helper.field_class='col-lg-10'
    form.helper.add_input(Submit('submit','Finalitzar compra'))
    return render(request,'carts/confirmation_form.html',{'form':form})

@user_passes_test(lambda u:u.is_authenticated(), login_url='/login/')
def llista_comandes(request):
    cmd=Comanda.objects.filter(usuari=request.user)
    return render(request,'carts/sales_list.html',{'comandes':cmd})

@user_passes_test(lambda u:u.is_authenticated(), login_url='/login/')
def detall_comanda(request,comanda_id):
    preu_comanda=0
    ui_comanda=[]
    lns=Linia.objects.filter(comanda_id=comanda_id)
    for lna in lns.all():
        pdt=Producte.objects.get(id=lna.producte_id.id)
        qnt=lna.quantitat
        pre=lna.preu*qnt
        preu_comanda+=pre
        ui_comanda.append({'producte':pdt,
                           'quantitat':qnt,
                           'preu':pre
                           })
    return render(request,'carts/detail.html',{'ui_comanda':ui_comanda,'preu_comanda':preu_comanda})

carts/templates/carts/cart.html
{% extends 'base.html' %} {% load staticfiles %} {% block css %}
<!-- Base Design -->
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<!-- No More Tables -->
<link href="{% static 'css/no-more-tables.css' %}" rel="stylesheet"> {% endblock %} {% block content %}
<div class="panel-heading">Llista de productes</div>
<div class="panel-body">
    {% if ui_cart %}
    <div class="table-responsive">
        <table id="no-more-tables" class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Imatge</th>
                    <th>Unitats</th>
                    <th>Preu</th>
                    <th>Editar</th>
                </tr>
            </thead>
            <tbody>
                {% for carret in ui_cart %}
                <tr>
                    <td data-title="Nom">{{carret.producte.nom}}</td>
                    <td data-title="Imatge">
                        <img src="{{carret.producte.imatge.url}}" style="width:100px;">
                    </td>
                    <td data-title="Unitats">{{carret.quantitat}}</td>
                    <td data-title="Preu">{{carret.preu}} €</td>
                    <td data-title="Editar">
                        <div class="btn-group">
                            <a class="wall-entry" href="{% url 'carts:actualitzarCarret' carret.producte.id %}"><span class="glyphicon glyphicon-minus"></span> <span class="glyphicon glyphicon-plus"></span></a>
                            <a class="wall-entry" href="{% url 'carts:esborrarLinia' carret.producte.id %}"><span class="glyphicon glyphicon-trash"></span></a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <th class="text-right th-hidden" colspan="4">Preu total</th>
                    <td data-title="Total">{{preu_comanda}} €</td>
                </tr>
            </tbody>
        </table>
        <div class="btn-group">
            <a class="btn btn-info" role="button" href="{% url 'carts:esborrarComanda' %}"><span class="glyphicon glyphicon-remove"></span> Cancel·lar comanda</a>
            <a class="btn btn-primary" role="button" href="{% url 'carts:confirmarCarret' %}"><span class="glyphicon glyphicon-ok"></span> Confirmar comanda</a>
        </div>
    </div>
    {% else %}
    <p>No hi han productes en el carret.</p>
    {% endif %}
</div>
{% endblock %}

carts/templates/carts/confirmation_form.html
{% extends 'base.html' %} {% load staticfiles %} {% load crispy_forms_tags %} {% block content %}
<div class="panel-heading">Finalitzar Comanda</div>
<div class="panel-body">
    {% crispy form %}
</div>
{% endblock %}

carts/templates/carts/detail.html
{% extends 'base.html' %} {% load staticfiles %} {% block css %}
<!-- Base Design -->
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<!-- No More Tables -->
<link href="{% static 'css/no-more-tables.css' %}" rel="stylesheet"> {% endblock %} {% block content %}
<div class="panel-heading">
    Detall de la comanda
    <div class="pull-right"><a class="wall-entry" href="{% url 'carts:llistaComandes' %}"><span class="glyphicon glyphicon-arrow-left"></span> Enrere</a></div>
</div>
<div class="panel-body">
    {% if ui_comanda %}
    <div class="table-responsive">
        <table id="no-more-tables" class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th class="th-hidden">Imatge</th>
                    <th>Unitats</th>
                    <th>Preu</th>
                </tr>
            </thead>
            <tbody>
                {% for comanda in ui_comanda %}
                <tr>
                    <td data-title="Nom">{{comanda.producte.nom}}</td>
                    <td class="td-hidden"><img src="{{comanda.producte.imatge.url}}" alt="{{comanda.producte.nom}}" style="width:100px;"></td>
                    <td data-title="Unitats">{{comanda.quantitat}}</td>
                    <td data-title="Preu">{{comanda.preu}} €</td>
                </tr>
                {% endfor %}
                <tr>
                    <th class="text-right th-hidden" colspan="3">Preu total</th>
                    <td data-title="Total">{{preu_comanda}} €</td>
                </tr>
            </tbody>
        </table>
    </div>
    {% else %}
    <p>No hi ha cap comanda amb aquest número de ID.</p>
    {% endif %}
</div>
{% endblock %}

carts/templates/carts/edit_cart.html
{% extends 'base.html' %} {% load staticfiles %} {% load crispy_forms_tags %} {% block css %}
<!-- Base Design -->
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<!-- Cart Design -->
<link href="{% static 'css/cart.css' %}" rel="stylesheet">
<!-- No More Tables -->
<link href="{% static 'css/no-more-tables.css' %}" rel="stylesheet"> {% endblock %} {% block content %}
<div class="panel-heading">Afegint al carret</div>
<div class="panel-body">
    <div class="panel-body">
        {% if producte %}
        <form id="form" method="post">
            <div class="table-responsive">
                <table id="no-more-tables" class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Imatge</th>
                            <th>Unitats</th>
                            <th>Preu</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td data-title="Nom">{{producte.nom}}</td>
                            <td data-title="Imatge">
                                <img src="{{producte.imatge.url}}" style="width:100px;">
                            </td>
                            <td data-title="Unitats">{% crispy form %}</td>
                            <td data-title="Preu">{{producte.preu}} €</td>
                        </tr>
                    </tbody>
                </table>
                <div class="btn-group">
                    <a class="btn btn-info" role="button" href="{{request.META.HTTP_REFERER}}"><span class="glyphicon glyphicon-remove"></span> Enrere</a>
                    <button class="btn btn-primary" role="button" type="submit" form="form" value="Submit"><span class="glyphicon glyphicon-ok"></span> Confirmar producte</button>
                </div>
            </div>
        </form>
        {% else %}
        <p>La ID del producte no és vàlida.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

carts/templates/carts/sales_list.html
{% extends 'base.html' %} {% load staticfiles %} {% block css %}
<!-- Base Design -->
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<!-- No More Tables -->
<link href="{% static 'css/no-more-tables.css' %}" rel="stylesheet"> {% endblock %} {% block content %}
<div class="panel-heading">Llista de comandes</div>
<div class="panel-body">
    {% if comandes %}
    <div class="table-responsive">
        {% for comanda in comandes reversed %}
        <table id="no-more-tables" class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Nº comanda</th>
                    <th>Data</th>
                    <th>Estat</th>
                    <th>Detall</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td data-title="Nº Com.">{{comanda.comanda_id}}</td>
                    <td data-title="Data">{{comanda.data}}</td>
                    <td data-title="Estat">{{comanda.get_estat_display}}</td>
                    <td data-title="Detall">
                        <div class="btn-group">
                            <a class="btn btn-primary" role="button" href="{% url 'carts:detallComanda' comanda.comanda_id %}">
                                <span class="glyphicon glyphicon-zoom-in"></span>
                            </a>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
        {% endfor %}
    </div>
    {% else %}
    <p>No hi ha cap comanda realitzada.</p>
    {% endif %}
</div>
{% endblock %}