backups/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^export_xml/$', views.export_xml, name='exportXML'),
    url(r'^import_xml/$', views.import_xml, name='importXML')
]

carts/urls.py
from django.conf.urls import url
from carts import views

urlpatterns = [
    url(r'^update_cart/(?P<item_id>[0-9]+)/$', views.actualitzar_carret, name='actualitzarCarret'),
    url(r'^show_sales_order/$', views.veure_comanda, name='veureComanda'),
    url(r'^show_sales_order/cart_confirmation/$', views.confirmar_carret, name='confirmarCarret'),
    url(r'^show_sales_order/delete_line/(?P<item_id>[0-9]+)/$', views.esborrar_linia, name='esborrarLinia'),
    url(r'^show_sales_order/delete_sales_order/$', views.esborrar_comanda, name='esborrarComanda'),
    url(r'^sales_list/$', views.llista_comandes, name='llistaComandes'),
    url(r'^sales_list/order_details/(?P<comanda_id>[0-9]+)/$', views.detall_comanda, name='detallComanda')
]

items/urls.py
from django.conf.urls import url
from items import views

urlpatterns = [
    url(r'^$', views.items, name='items'),
    url(r'^item/', views.infoitem, name='infoItem'),
    url(r'^add_item/$', views.item, name='addItem'),
    url(r'^edit_item/(?P<item_id>[0-9]+)/$', views.item, name='editItem'),
    url(r'^remove_item/(?P<item_id>[0-9]+)/$', views.removeitem, name='removeItem'),
    url(r'^categories/$', views.categories, name='categories'),
    url(r'^add_category/$', views.category, name='addCategory'),
    url(r'^edit_category/(?P<category_id>[0-9]+)/$', views.category, name='editCategory'),
    url(r'^remove_category/(?P<category_id>[0-9]+)/$', views.removecategory, name='removeCategory'),
    url(r'^manufacturers/$', views.manufacturers, name='manufacturers'),
    url(r'^add_manufacturer/$', views.manufacturer, name='addManufacturer'),
    url(r'^edit_manufacturer/(?P<manufacturer_id>[0-9]+)/$', views.manufacturer, name='editManufacturer'),
    url(r'^remove_manufacturer/(?P<manufacturer_id>[0-9]+)/$', views.removemanufacturer, name='removeManufacturer')
]

sun2/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from users.views import vista_login, vista_logout, vista_registre, vista_perfil, vista_clau

urlpatterns = (
    [
        url(r'^admin/', admin.site.urls),
        url(r'^', include('items.urls', namespace="items")),
        url(r'^cart/', include('carts.urls', namespace="carts")),
        url(r'^backups/', include('backups.urls', namespace="backups")),
        url(r'^login/$', vista_login, name="login"),
        url(r'^logout/$', vista_logout, name="logout"),
        url(r'^registration/$', vista_registre, name="registration"),
        url(r'^profile/$', vista_perfil, name="profile"),
        url(r'^profile/reset/$', vista_clau, name="resetPassword")
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

templates/partials/layout_messages.html
<div class="col-xs-12 col-sm-12 col-md-12">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="alert {% if message.tags %} alert-{{message.tags}} {% endif %}">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{message}}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

templates/partials/layout_modal.html
<div id="modal-item" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">[[Producte.nom]]</h4>
            </div>
            <div class="modal-body text-justify">
                <p>[[Producte.resum]]</p>
            </div>
            <div ng-if="Producte.video" class="modal-footer">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe ng-src="[[Producte.video]]" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</div>

templates/partials/navbar_users.html
{% if user.is_anonymous %}
<li>
    <a href="{% url 'login' %}">Login</a>
</li>
{% else %} {% if user.is_staff %}
<li class="dropdown">
    <a href="#" class="dropdown-toggle capitalize" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{request.user.username}} <span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a href="{% url 'items:items' %}"><span class="glyphicon glyphicon-list-alt dropdown-li-space"></span> Mostrar Producte</a></li>
        <li><a href="{% url 'items:categories' %}"><span class="glyphicon glyphicon-list-alt dropdown-li-space"></span> Mostrar Categoria</a></li>
        <li><a href="{% url 'items:manufacturers' %}"><span class="glyphicon glyphicon-list-alt dropdown-li-space"></span> Mostrar Fabricant</a></li>
        <li><a href="{% url 'items:addItem' %}"><span class="glyphicon glyphicon-plus dropdown-li-space"></span> Afegir Producte</a></li>
        <li><a href="{% url 'items:addCategory' %}"><span class="glyphicon glyphicon-plus dropdown-li-space"></span> Afegir Categoria</a></li>
        <li><a href="{% url 'items:addManufacturer' %}"><span class="glyphicon glyphicon-plus dropdown-li-space"></span> Afegir Fabricant</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="{% url 'backups:exportXML' %}"><span class="glyphicon glyphicon glyphicon-export dropdown-li-space"></span> Exportar dades a XML</a></li>
        <li><a href="{% url 'backups:importXML' %}"><span class="glyphicon glyphicon glyphicon-export dropdown-li-space"></span> Importar dades a XML</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out dropdown-li-space"></span> Sortir</a></li>
    </ul>
</li>
{% else %}
<li class="dropdown">
    <a href="#" class="dropdown-toggle capitalize" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{request.user.username}} <span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a href="{% url 'profile' %}"><span class="glyphicon glyphicon-wrench dropdown-li-space"></span> Editar el perfil</a></li>
        <li><a href="{% url 'carts:llistaComandes' %}"><span class="glyphicon glyphicon-tag dropdown-li-space"></span> Les meves compres</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out dropdown-li-space"></span> Sortir</a></li>
    </ul>
</li>
{% endif %} {% endif %}