carts/urls.py
from django.conf.urls import url
from carts import views

urlpatterns = [
    url(r'^update_cart/(?P<item_id>[0-9]+)/$', views.actualitzar_carret, name='actualitzarCarret'),
    url(r'^show_sales_order/$', views.veure_comanda, name='veureComanda'),
    url(r'^show_sales_order/cart_confirmation/$', views.confirmar_carret, name='confirmarCarret'),
    url(r'^show_sales_order/delete_line/(?P<item_id>[0-9]+)/$', views.esborrar_linia, name='esborrarLinia'),
    url(r'^show_sales_order/delete_sales_order/$', views.esborrar_comanda, name='esborrarComanda'),
    url(r'^sales_list/$', views.llista_comandes, name='llistaComandes'),
    url(r'^sales_list/order_details/(?P<comanda_id>[0-9]+)/$', views.detall_comanda, name='detallComanda')
]

items/urls.py
from django.conf.urls import url
from items import views

urlpatterns = [
    url(r'^$', views.items, name='items'),
    url(r'^item/', views.infoitem, name='infoItem'),
    url(r'^add_item/$', views.item, name='addItem'),
    url(r'^edit_item/(?P<item_id>[0-9]+)/$', views.item, name='editItem'),
    url(r'^remove_item/(?P<item_id>[0-9]+)/$', views.removeitem, name='removeItem'),
    url(r'^categories/$', views.categories, name='categories'),
    url(r'^add_category/$', views.category, name='addCategory'),
    url(r'^edit_category/(?P<category_id>[0-9]+)/$', views.category, name='editCategory'),
    url(r'^remove_category/(?P<category_id>[0-9]+)/$', views.removecategory, name='removeCategory'),
    url(r'^manufacturers/$', views.manufacturers, name='manufacturers'),
    url(r'^add_manufacturer/$', views.manufacturer, name='addManufacturer'),
    url(r'^edit_manufacturer/(?P<manufacturer_id>[0-9]+)/$', views.manufacturer, name='editManufacturer'),
    url(r'^remove_manufacturer/(?P<manufacturer_id>[0-9]+)/$', views.removemanufacturer, name='removeManufacturer')
]

sun2/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from users.views import vista_login, vista_logout, vista_registre, vista_perfil, vista_clau

urlpatterns = (
    [
        url(r'^admin/', admin.site.urls),
        url(r'^', include('items.urls', namespace="items")),
        url(r'^cart/', include('carts.urls', namespace="carts")),
        url(r'^backups/', include('backups.urls', namespace="backups")),
        url(r'^login/$', vista_login, name="login"),
        url(r'^logout/$', vista_logout, name="logout"),
        url(r'^registration/$', vista_registre, name="registration"),
        url(r'^profile/$', vista_perfil, name="profile"),
        url(r'^profile/reset/$', vista_clau, name="resetPassword")
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

users/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

users/forms.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder':'Introdueix el teu usuari','autofocus':'autofocus'}))
    password = forms.CharField(min_length=5, max_length=100, widget=forms.PasswordInput(attrs={'placeholder':'Introdueix el teu password'}))

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder':'Introdueix el teu nom d\'usuari','autofocus':'autofocus'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'Introdueix el teu correu electrònic'}))
    password = forms.CharField(min_length=5, max_length=100, widget=forms.PasswordInput(attrs={'placeholder':'Introdueix el teu password'}))
    repeat_password = forms.CharField(min_length=5, max_length=100, widget=forms.PasswordInput(attrs={'placeholder':'Repeteix el teu password'}))

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username):
            raise forms.ValidationError('El nom d\'usuari ja està ocupat')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError('El correu electrònic ja està registrat')
        return email

class ChangePasswordForm(forms.Form):
    password = forms.CharField(min_length=5, max_length=100, widget=forms.PasswordInput(attrs={'placeholder':'Introdueix el teu nou password'}))
    repeat_password = forms.CharField(min_length=5, max_length=100, widget=forms.PasswordInput(attrs={'placeholder':'Repeteix el teu nou password'}))

users/views.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import user_passes_test
from django.views.decorators.csrf import csrf_protect
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit
from users.forms import LoginForm, RegistrationForm, ChangePasswordForm

@csrf_protect
def vista_login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('items:items'))
    else:
        if request.method=='POST':
            form=LoginForm(request.POST)
            if form.is_valid():
                username=form.cleaned_data['username']
                password=form.cleaned_data['password']
                seguent=request.GET.get('next',default=None)
                user=authenticate(username=username,password=password)
                if user is not None:
                    if user.is_active:
                        login(request,user)
                        if bool(seguent):
                            return HttpResponseRedirect(seguent)
                        else:
                            return HttpResponseRedirect(reverse('items:items'))
                    else:
                        messages.error(request,'Usuari desactivat')
                        return HttpResponseRedirect(reverse('login'))
                else:
                    messages.error(request,'Error, usuari i/o contrasenya són/és incorrectes/e/a')
                    return HttpResponseRedirect(reverse('login'))
            else:
                messages.error(request,'Hi ha errors en el formulari')
        else:
            form=LoginForm()

    form.helper=FormHelper()
    form.helper.form_class='form-horizontal'
    form.helper.add_input(Submit('submit','Login'))

    return render(request,'forms/login.html',{'form':form})

@csrf_protect
def vista_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('items:items'))

@csrf_protect
def vista_registre(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('items:items'))
    else:
        if request.method=='POST':
            form=RegistrationForm(request.POST)
            if form.is_valid():
                cleaned_data=form.cleaned_data
                username=cleaned_data.get('username')
                password=cleaned_data.get('password')
                email=cleaned_data.get('email')
                User.objects.create_user(username=username,password=password,email=email)
                messages.success(request,'Usuari registrat correctament')
                return HttpResponseRedirect(reverse('login'))
            else:
                messages.error(request,"Hi ha errors en el formulari")
        else:
            form=RegistrationForm()

    form.helper=FormHelper()
    form.helper.form_class='form-horizontal'
    form.helper.add_input(Submit('submit','Registrar-se'))

    return render(request,'forms/registration.html',{'form':form})

@user_passes_test(lambda u:u.is_authenticated(), login_url='/login/')
def vista_perfil(request):
    user=request.user
    context={'user':user}
    return render(request,'user.html',context)

@user_passes_test(lambda u:u.is_authenticated(), login_url='/login/')
def vista_clau(request):
    if request.method=='POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            cleaned_data=form.cleaned_data
            password=cleaned_data.get('password')
            user=request.user
            user.set_password(password)
            user.save()
            logout(request)
            messages.success(request,'La clau s\'ha modificat correctament')
            return HttpResponseRedirect(reverse('login'))
        else:
            messages.error(request,"Hi ha errors en el formulari")
    else:
        form=ChangePasswordForm()

    form.helper=FormHelper()
    form.helper.form_class='form-horizontal'
    form.helper.add_input(Submit('submit','Desar'))

    return render(request,'forms/registration.html',{'form':form})

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ca">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>SunDos</title>
    <link href="{% static 'icon/favicon.ico' %}" rel="shortcut icon" /> {% block css %}
    <!-- Base Design -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet"> {% endblock %}
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- FontAwesome -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- Bootstrap Social Icons -->
    <link href="{% static 'css/bootstrap-social.css' %}" rel="stylesheet">
</head>

<body ng-app="appSunDos">
    {% block body %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'items:items' %}">SunDos</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    {% block navbar %} {% endblock %}
                    <ul class="nav navbar-nav navbar-right">
                        {% if not user.is_staff %}
                        <li>
                            <a href="{% url 'carts:veureComanda' %}">
                                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> {% if carret_ple %}
                                <div id="red-cart">{{valor}}</div> {% endif %}
                            </a>
                        </li>
                        {% endif %} {% include 'partials/navbar_users.html' %}
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <section class="container">
        {% include 'partials/layout_messages.html' %}
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div id="panel-base" class="panel panel-default">
                {% block content %} {% endblock %}
            </div>
        </div>
    </section>
    {% endblock %}

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js" type="text/javascript"></script>
    <!-- Bootstrap Scripts -->
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    {% block scripts %} {% endblock %}
</body>

</html>

templates/user.html
{%extends 'base.html' %} {% load staticfiles %} {% block css %}
<!-- Base Design -->
<link href="{% static 'css/base.css' %}" rel="stylesheet"> {% endblock %} {% block content %}
<div class="panel-heading">Editar el perfil</div>
<div class="panel-body">
    <div class="jumbotron text-justify" style="padding:2em 1em 1em 2em;">
        <p>Hola, benvingut/da a la nostre botiga. <span class="capitalize">{{user.username}}</span>, si vols veure les teves comandes fes <a href="{% url 'carts:llistaComandes' %}">clic aquí</a>.</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-8">
        <table class="table table-hover table-bordered table-striped">
            <tbody>
                <tr>
                    <td colspan="2"><small>Dades de l'usuari</small></td>
                </tr>
                <tr>
                    <th class="th-hidden">Usuari</th>
                    <td class="capitalize">{{user.username}}</td>
                </tr>
                <tr>
                    <th class="th-hidden">Correu electrònic</th>
                    <td>{{user.email}}</td>
                </tr>
                <tr>
                    <th class="th-hidden">Modificar contrasenya</th>
                    <td>
                        <a class="wall-entry" href="{% url 'resetPassword' %}">
                            Canviar la contrasenya
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}